# Generated by Django 4.2.5 on 2024-02-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skisubuser',
            name='account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
