# Generated by Django 4.2.5 on 2024-03-01 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_skisubuser_account_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionId', models.CharField(max_length=50)),
                ('initiationTranRef', models.CharField(blank=True, max_length=50)),
                ('accountNumber', models.CharField(max_length=20)),
                ('tranRemarks', models.CharField(blank=True, max_length=255)),
                ('transactionAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('settledAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('feeAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vatAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(max_length=3)),
                ('settlementId', models.CharField(max_length=50)),
                ('sourceAccountNumber', models.CharField(blank=True, max_length=20)),
                ('sourceAccountName', models.CharField(blank=True, max_length=255)),
                ('sourceBankName', models.CharField(blank=True, max_length=255)),
                ('channelId', models.CharField(blank=True, max_length=50)),
                ('tranDateTime', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
