# Generated by Django 4.2.5 on 2024-02-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skisub', '0002_delete_skisubuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billoperation',
            old_name='destination',
            new_name='rechargeplan',
        ),
        migrations.RemoveField(
            model_name='billoperation',
            name='departdate',
        ),
        migrations.RemoveField(
            model_name='billoperation',
            name='flightclass',
        ),
        migrations.RemoveField(
            model_name='billoperation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='billoperation',
            name='passenger',
        ),
        migrations.AlterField(
            model_name='billoperation',
            name='billclass',
            field=models.CharField(blank=True, choices=[('recharge_card', 'recharge_card'), ('data', 'data'), ('sme_data', 'sme_data'), ('electricity', 'electricity'), ('cabletv', 'cabletv')], default='sme_data', max_length=250, null=True),
        ),
    ]
