# Generated by Django 4.2.5 on 2024-07-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skisub', '0002_utilityorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billoperation',
            name='billclass',
        ),
        migrations.RemoveField(
            model_name='billoperation',
            name='serviceops',
        ),
        migrations.AddField(
            model_name='billoperation',
            name='bill_class',
            field=models.CharField(blank=True, choices=[('recharge_card', 'recharge_card'), ('data', 'data'), ('electricity', 'electricity'), ('cabletv', 'cabletv')], default='data', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='billoperation',
            name='service_ops',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
