# Generated by Django 4.2.5 on 2024-07-13 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skisub', '0003_remove_billoperation_billclass_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirtimeBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DataBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_volume', models.CharField(max_length=50)),
                ('validity_period', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('AIRTIME', 'Airtime'), ('DATA', 'Data')], max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_status', models.CharField(default='Pending', max_length=20)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('airtime_bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skisub.airtimebundle')),
                ('data_bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skisub.databundle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.RemoveField(
            model_name='utilityorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='utilityorder',
            name='utility',
        ),
        migrations.DeleteModel(
            name='BillOperation',
        ),
        migrations.DeleteModel(
            name='UtilityOrder',
        ),
        migrations.AddField(
            model_name='databundle',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_bundles', to='skisub.serviceprovider'),
        ),
        migrations.AddField(
            model_name='airtimebundle',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airtime_bundles', to='skisub.serviceprovider'),
        ),
    ]
