# Generated by Django 4.2.5 on 2024-03-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skisub', '0003_rename_destination_billoperation_rechargeplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billoperation',
            name='phone_no',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
