# Generated by Django 4.2.5 on 2024-03-05 14:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_location', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('adult_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('child_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('departure_date', models.DateField(default=datetime.date.today)),
                ('return_date', models.DateField(default=datetime.date.today)),
                ('trip_type', models.CharField(choices=[('one_way', 'One Way'), ('round_trip', 'Round Trip')], default='one_way', max_length=20)),
                ('select_class', models.CharField(choices=[('economy', 'Economy'), ('first_class', 'First Class')], default='economy', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults', models.PositiveIntegerField()),
                ('children', models.PositiveIntegerField()),
                ('departure_date', models.DateField(default=datetime.date.today)),
                ('return_date', models.DateField(default=datetime.date.today)),
                ('trip_type', models.CharField(choices=[('one_way', 'One Way'), ('round_trip', 'Round Trip')], default='one_way', max_length=20)),
                ('select_class', models.CharField(choices=[('economy', 'Economy'), ('first_class', 'First Class')], default='economy', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightbooking.flight')),
            ],
        ),
    ]
