# Generated by Django 4.2.5 on 2024-08-03 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carbook', '0003_booking_dropoff_location_booking_pickup_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
        migrations.AddField(
            model_name='car',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='cars', to='carbook.carimage'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='air_conditioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='max_power_hp',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbook.carmodel'),
        ),
        migrations.AlterField(
            model_name='car',
            name='number_of_doors',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='number_of_passengers',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='top_speed_mph',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=20),
        ),
    ]
