# Generated by Django 4.2.5 on 2024-08-03 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbook', '0004_remove_car_image_car_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='images',
            new_name='image',
        ),
    ]
