# Generated by Django 4.2.5 on 2024-08-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.IntegerField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='hotelorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
