name: Production Build and Test

on:
  push:
    branches: [main]

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   services:
  #     postgres:
  #       image: postgres:latest
  #       env:
  #         POSTGRES_USER: postgres
  #         POSTGRES_PASSWORD: 1234567
  #         POSTGRES_DB: ncpdb
  #       ports:
  #         - 5432:5432
  #       options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2
  #   - name: Set up Python Environment
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: '3.x'
  #   - name: Install psycopg2 prerequisites
  #     run: sudo apt-get install libpq-dev
  #   - name: Install Dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install -r requirements.txt
  #   - name: Run migrations
  #     run: python manage.py migrate --settings=skisub.settings.github
  #   - name: Run Tests
  #     run: |
  #       python manage.py test --settings=skisub.settings.github

  deploy:
    # needs: [test]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: skis
        environment_name: Skis-env
        version_label: prod.${{github.run_number}}
        version_description: none
        region: "eu-west-1"
        deployment_package: deploy.zip
        use_existing_version_if_available: true
